### Check GPU is Sync with CUDA

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

import os



In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

if device.type == "cuda":
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("GPU Count:", torch.cuda.device_count())
    print("Current GPU Index:", torch.cuda.current_device())
else:
    print("Running on CPU")

Device: cuda
GPU Name: NVIDIA GeForce RTX 3090
GPU Count: 1
Current GPU Index: 0


#### Basic Perceptron

##### Single Layer Neural Network

In [3]:
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        self.input_size = input_size
        
        self.weight = nn.Parameter(torch.randn(input_size))
        self.bias = nn.Parameter(torch.zeros(1))
        
        print(self.weight, self.bias)
    
    
    
    # def forward(self, x):
    #     pass


    def forward(self, x):
        z= x@self.weight + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred



# create object (OUTSIDE class)
perceptron = Perceptron(5)

Parameter containing:
tensor([ 0.4806,  0.9690,  0.1622, -1.6914, -1.6452], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


##### Save model to local directory

In [4]:
model = Perceptron(input_size =3)
model_path= 'my_model.pth'


if os.path.exists(model_path):
    model.load_state_dict(torch.load(model_path))
    print("Model Loaded")

Parameter containing:
tensor([-1.9718, -1.5844, -1.0837], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [5]:
x = torch.randn(3)
print(x)

y_pred = model(x)
print(y_pred)

tensor([ 0.1084, -1.3720,  0.5087])
tensor([0.8035], grad_fn=<SigmoidBackward0>)


##### Cost function & Optimizer

In [6]:
criterion = nn.BCELoss   # Binary cross entropy

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0001                ## lr is learning rate
)

In [7]:
model = Perceptron(4)


X = torch.tensor([
    [0.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [1.0, 0.0, 0.0, 0.0],
    [1.0, 1.0, 1.0, 0.0]
])

Y = torch.tensor([
    [0.0],
    [0.0],
    [0.0],
    [1.0]
])

y_pred = model(X)
print("Prediction:", y_pred)

Parameter containing:
tensor([-0.0499, -0.5967,  0.2965, -0.1641], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)
Prediction: tensor([0.5000, 0.3551, 0.4875, 0.4133], grad_fn=<SigmoidBackward0>)


In [11]:
print(os.getcwd())

/home/kamran/Desktop/Work/python_vs_code/20260405_ml_ops/20260405_bongodev
