In [1]:
import torch
torch.cuda.is_available()

False

In [2]:
import torch.nn as nn 
import numpy as np

In [3]:
X = np.array([
     [0.0, 0.0],
     [0.0, 1.0],
     [1.0, 0.0],
     [1.0, 1.0]
])

print(X)
print(type(X))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [4]:
X= torch.tensor(X)
print(type(X))

<class 'torch.Tensor'>


In [5]:
print(np.random.rand(5))



my_tesnor= torch.rand(5)
print(my_tesnor)
print(my_tesnor.sum())


[0.11189214 0.24054076 0.55073902 0.79512655 0.59758438]
tensor([0.8645, 0.9486, 0.0755, 0.8579, 0.1093])
tensor(2.8559)
